#!/bin/sh
# Container start-up: write the SPA's runtime config from the environment, then hand
# off to nginx.
#
# This is what makes ONE image serve every environment. Vite inlines VITE_* at build
# time, so a bundle is normally welded to the API origin it was built with; here the
# app reads window.APP_CONFIG from /config.js instead (src/services/config.js), and
# this script regenerates that file on every start. Repointing a deployment is an env
# change + restart, not a rebuild.
#
# Names are accepted with or without the VITE_ prefix, so the same variables work for
# a local build and for a running container.
set -eu

CONFIG=/usr/share/nginx/html/config.js

API_URL="${API_URL:-${VITE_API_URL:-}}"
AUTO_GUEST="${AUTO_GUEST:-${VITE_AUTO_GUEST:-}}"
AUTO_GUEST_PREFIX="${AUTO_GUEST_PREFIX:-${VITE_AUTO_GUEST_PREFIX:-}}"
# Debug x-ray. Runtime-settable on purpose: you can flip it on a running container to
# chase a bug and flip it back off, without a rebuild.
DEBUG_PEEK="${DEBUG_PEEK:-${VITE_DEBUG_PEEK:-}}"

# These land inside a JS string literal, and they're arbitrary operator input — a
# stray quote or backslash would produce a file that fails to parse and take the whole
# app down with a blank screen.
esc() { printf '%s' "${1:-}" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'; }

cat > "$CONFIG" <<EOF
// Generated by entrypoint.sh at container start — edits here are lost on restart.
window.APP_CONFIG = {
  API_URL: "$(esc "$API_URL")",
  AUTO_GUEST: "$(esc "$AUTO_GUEST")",
  AUTO_GUEST_PREFIX: "$(esc "$AUTO_GUEST_PREFIX")",
  DEBUG_PEEK: "$(esc "$DEBUG_PEEK")",
};
EOF

echo "entrypoint: wrote $CONFIG  API_URL=${API_URL:-<unset, using build default>}  AUTO_GUEST=${AUTO_GUEST:-<unset>}"
# `if`, not `[ … ] && echo`: under `set -e` a false test would make the whole script
# exit non-zero and the container would never start nginx.
if [ "$DEBUG_PEEK" = "true" ]; then
  echo "entrypoint: *** DEBUG_PEEK IS ON — every player can see every hand. Never ship this. ***"
fi

# nginx's own entrypoint still runs (it handles /docker-entrypoint.d, permissions and
# the final exec) — this only prepends a step.
exec /docker-entrypoint.sh "$@"
